// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxgntmcfrdqlwjehxpss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4Z250bWNmcmRxbHdqZWh4cHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjE4NDYsImV4cCI6MjA2ODA5Nzg0Nn0.TEr-Bn53l1Fb-69kVPY3qsZksyqwfQFQeJsrJso5hc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});